version: 1.1.{build}
image: Visual Studio 2022
branches:
  only:
    - master
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
pull_requests:
  do_not_increment_build_number: true
build_script:
- cmd: >-
    dotnet pack src\SshKeyGenerator.csproj -c Release -p:Version=%APPVEYOR_BUILD_VERSION% -o \projects\sshkeygenerator\nuget-packed
artifacts:
- path: nuget-packed\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: nuzhFMwlMnsTpDpFu6ngFFcTKwx5A1Dl90RtY0WHKORV4Z0nN7jCg8XGgrjy7TCB
  
