version: 1.1.{build}
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
pull_requests:
  do_not_increment_build_number: true
build_script:
- cmd: >-
    dotnet pack src\SshKeyGenerator.csproj -c Release -p:Version=%APPVEYOR_BUILD_VERSION% -o \projects\sshkeygenerator\nuget-packed
artifacts:
- path: nuget-packed\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: cG4B/YEJ3W+ndQBsP2zJMR5tmirzrFuP5g5RfgSpTm9uFIXl1yoDVwd9cCambiqn
  
